### ISSUE TITLE
打印row值，但是把所有的值都打印出来了

### ISSUE THREAD

**Issue by kemisstep** [mmdctjj/raetable#1]
const editData = () => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve({
                msg: 'ok',
                code: 200,
            });
            console.log('editData', datas)
        }, 1000);
    });
};

实际上只想打印编辑这一列

**Comment by mmdctjj** [comment]
抱歉，今天才看到，这个函数对应的上下文可以提供下吗，我想知道这个函数是在啥地方调用的

**Comment by kemisstep** [comment]
> 抱歉，今天才看到，这个函数对应的上下文可以提供下吗，我想知道这个函数是在啥地方调用的

这个是函数用错了，已解决了
